### ISSUE TITLE
Shapes are incompatible

### ISSUE THREAD

**Issue by endymecy** [skywaLKer518/recsys#1]
I use tensorflow r0.12 to run ml-1m dataset and i get the following error.

Traceback (most recent call last):
  File "/home/endy/PycharmProjects/recommender/lstm/run.py", line 720, in <module>
    main()
  File "/home/endy/PycharmProjects/recommender/lstm/run.py", line 717, in main
    train()
  File "/home/endy/PycharmProjects/recommender/lstm/run.py", line 360, in train
    train_set, dev_set, test_set, embAttr, START_ID, item_population, p_item, _, _ = read_data(task)
  File "/home/endy/PycharmProjects/recommender/lstm/run.py", line 299, in read_data
    embAttr = embed_attribute.EmbeddingAttribute(u_attr, i_attr, FLAGS.batch_size, FLAGS.n_sampled, _buckets[-1], FLAGS.use_sep_item, item_ind2logit_ind, logit_ind2item_ind, devices=devices)
  File "/home/endy/PycharmProjects/recommender/lstm/attributes/embed_attribute.py", line 116, in __init__
    self.update_sampled = self._pass_sampled_items(prefix, device=devices[-1])
  File "/home/endy/PycharmProjects/recommender/lstm/attributes/embed_attribute.py", line 337, in _pass_sampled_items
    mulhot_indices = batch_slice2(self.att[prefix][1][i], b, s, self.n_sampled)
  File "/home/endy/PycharmProjects/recommender/lstm/attributes/mulhot_index.py", line 46, in batch_slice2
    return tf.concat(res, 0)
  File "/home/endy/.virtualenvs/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1122, in concat
    ).assert_is_compatible_with(tensor_shape.scalar())
  File "/home/endy/.virtualenvs/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 756, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (1024, ?) and () are incompatible

**Comment by skywaLKer518** [comment]
We are working on a simplified data pre-processing interface and a complete testing example. I'll get back to this.

**Comment by skywaLKer518** [comment]
We updated the input interface. ml-1m example dataset is also provided. Please let me know if you still have the issue.

**Comment by endymecy** [comment]
what tensorflow version you use?

**Comment by skywaLKer518** [comment]
we used 0.8, 0.9, 0.11, 0.12 at different time during development. The example scripts are tested on 0.12.
0.11, 0.12 gives considerable speed up by running some ops (like unsorted segment sum) on GPUs.
